### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lbenezra-FA**
## Description & motivation

The advanced cloud usage section for the compare-column-values was incorrect, and needed more code / explanation for it to work properly. 

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)

### CODE REVIEW

**Comment by joellabes** [comment]
Do you think we should instead ship a `print_results_cloud()` macro that takes `audit_results` as input? so it would basically be: 

## Core
```
{% set audit_results = run_query(audit_query) %}

{% if execute %}
{% do audit_results.print_table() %}
{% endif %}
```

## Cloud
```
{% set audit_results = run_query(audit_query) %}

{% if execute %}
{% audit_helper.print_results_cloud(audit_results) %}
{% endif %}
```

This feels nicer than making people create the macro themselves, wdyt?

**Comment by lbenezra-FA** [comment]
@joellabes YES!!! love. that would be epic.

**Comment by lbenezra-FA** [comment]
Can we merge this working option in the meantime?

**Comment by joellabes** [comment]
Yeah this is just a readme change so let's do it!

**Review by joellabes — APPROVED** [review]

**Pull request merged**
